# 这些是支持的资金模型平台

github: # 用最多4个启用了GitHub赞助的用户名替换，例如[user1, user2]
patreon: camenduru
open_collective: # 用一个Open Collective的用户名替换
ko_fi: camenduru
tidelift: # 用一个Tidelift平台名/包名替换，例如npm/babel
community_bridge: # 用一个Community Bridge项目名替换，例如cloud-foundry
liberapay: # 用一个Liberapay用户名替换
issuehunt: # 用一个IssueHunt用户名替换
otechie: # 用一个Otechie用户名替换
lfx_crowdfunding: # 用一个LFX Crowdfunding项目名替换，例如cloud-foundry
custom: # 用最多4个自定义赞助URL替换，例如['link1', 'link2']
